/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutsIndexRouteImport } from './routes/workouts/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as ExercisesIndexRouteImport } from './routes/exercises/index'
import { Route as ActiveWorkoutIndexRouteImport } from './routes/active-workout/index'
import { Route as WorkoutsNewRouteImport } from './routes/workouts/new'
import { Route as WorkoutsImportRouteImport } from './routes/workouts/import'
import { Route as WorkoutsPlanIdRouteImport } from './routes/workouts/$planId'
import { Route as ProfileProgressRouteImport } from './routes/profile/progress'
import { Route as ProfileOptionalDaysRouteImport } from './routes/profile/optional-days'
import { Route as ProfileMeasurementsRouteImport } from './routes/profile/measurements'
import { Route as HistorySessionIdRouteImport } from './routes/history/$sessionId'
import { Route as ActiveWorkoutPlanIdRouteImport } from './routes/active-workout/$planId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIndexRoute = WorkoutsIndexRouteImport.update({
  id: '/workouts/',
  path: '/workouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActiveWorkoutIndexRoute = ActiveWorkoutIndexRouteImport.update({
  id: '/active-workout/',
  path: '/active-workout/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsNewRoute = WorkoutsNewRouteImport.update({
  id: '/workouts/new',
  path: '/workouts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsImportRoute = WorkoutsImportRouteImport.update({
  id: '/workouts/import',
  path: '/workouts/import',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsPlanIdRoute = WorkoutsPlanIdRouteImport.update({
  id: '/workouts/$planId',
  path: '/workouts/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileProgressRoute = ProfileProgressRouteImport.update({
  id: '/profile/progress',
  path: '/profile/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileOptionalDaysRoute = ProfileOptionalDaysRouteImport.update({
  id: '/profile/optional-days',
  path: '/profile/optional-days',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileMeasurementsRoute = ProfileMeasurementsRouteImport.update({
  id: '/profile/measurements',
  path: '/profile/measurements',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorySessionIdRoute = HistorySessionIdRouteImport.update({
  id: '/history/$sessionId',
  path: '/history/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ActiveWorkoutPlanIdRoute = ActiveWorkoutPlanIdRouteImport.update({
  id: '/active-workout/$planId',
  path: '/active-workout/$planId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/active-workout/$planId': typeof ActiveWorkoutPlanIdRoute
  '/history/$sessionId': typeof HistorySessionIdRoute
  '/profile/measurements': typeof ProfileMeasurementsRoute
  '/profile/optional-days': typeof ProfileOptionalDaysRoute
  '/profile/progress': typeof ProfileProgressRoute
  '/workouts/$planId': typeof WorkoutsPlanIdRoute
  '/workouts/import': typeof WorkoutsImportRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/active-workout/': typeof ActiveWorkoutIndexRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/active-workout/$planId': typeof ActiveWorkoutPlanIdRoute
  '/history/$sessionId': typeof HistorySessionIdRoute
  '/profile/measurements': typeof ProfileMeasurementsRoute
  '/profile/optional-days': typeof ProfileOptionalDaysRoute
  '/profile/progress': typeof ProfileProgressRoute
  '/workouts/$planId': typeof WorkoutsPlanIdRoute
  '/workouts/import': typeof WorkoutsImportRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/active-workout': typeof ActiveWorkoutIndexRoute
  '/exercises': typeof ExercisesIndexRoute
  '/history': typeof HistoryIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/workouts': typeof WorkoutsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/active-workout/$planId': typeof ActiveWorkoutPlanIdRoute
  '/history/$sessionId': typeof HistorySessionIdRoute
  '/profile/measurements': typeof ProfileMeasurementsRoute
  '/profile/optional-days': typeof ProfileOptionalDaysRoute
  '/profile/progress': typeof ProfileProgressRoute
  '/workouts/$planId': typeof WorkoutsPlanIdRoute
  '/workouts/import': typeof WorkoutsImportRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/active-workout/': typeof ActiveWorkoutIndexRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/active-workout/$planId'
    | '/history/$sessionId'
    | '/profile/measurements'
    | '/profile/optional-days'
    | '/profile/progress'
    | '/workouts/$planId'
    | '/workouts/import'
    | '/workouts/new'
    | '/active-workout/'
    | '/exercises/'
    | '/history/'
    | '/profile/'
    | '/workouts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/active-workout/$planId'
    | '/history/$sessionId'
    | '/profile/measurements'
    | '/profile/optional-days'
    | '/profile/progress'
    | '/workouts/$planId'
    | '/workouts/import'
    | '/workouts/new'
    | '/active-workout'
    | '/exercises'
    | '/history'
    | '/profile'
    | '/workouts'
  id:
    | '__root__'
    | '/'
    | '/active-workout/$planId'
    | '/history/$sessionId'
    | '/profile/measurements'
    | '/profile/optional-days'
    | '/profile/progress'
    | '/workouts/$planId'
    | '/workouts/import'
    | '/workouts/new'
    | '/active-workout/'
    | '/exercises/'
    | '/history/'
    | '/profile/'
    | '/workouts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActiveWorkoutPlanIdRoute: typeof ActiveWorkoutPlanIdRoute
  HistorySessionIdRoute: typeof HistorySessionIdRoute
  ProfileMeasurementsRoute: typeof ProfileMeasurementsRoute
  ProfileOptionalDaysRoute: typeof ProfileOptionalDaysRoute
  ProfileProgressRoute: typeof ProfileProgressRoute
  WorkoutsPlanIdRoute: typeof WorkoutsPlanIdRoute
  WorkoutsImportRoute: typeof WorkoutsImportRoute
  WorkoutsNewRoute: typeof WorkoutsNewRoute
  ActiveWorkoutIndexRoute: typeof ActiveWorkoutIndexRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  WorkoutsIndexRoute: typeof WorkoutsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/': {
      id: '/workouts/'
      path: '/workouts'
      fullPath: '/workouts/'
      preLoaderRoute: typeof WorkoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/exercises'
      fullPath: '/exercises/'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/active-workout/': {
      id: '/active-workout/'
      path: '/active-workout'
      fullPath: '/active-workout/'
      preLoaderRoute: typeof ActiveWorkoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/new': {
      id: '/workouts/new'
      path: '/workouts/new'
      fullPath: '/workouts/new'
      preLoaderRoute: typeof WorkoutsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/import': {
      id: '/workouts/import'
      path: '/workouts/import'
      fullPath: '/workouts/import'
      preLoaderRoute: typeof WorkoutsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/$planId': {
      id: '/workouts/$planId'
      path: '/workouts/$planId'
      fullPath: '/workouts/$planId'
      preLoaderRoute: typeof WorkoutsPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/progress': {
      id: '/profile/progress'
      path: '/profile/progress'
      fullPath: '/profile/progress'
      preLoaderRoute: typeof ProfileProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/optional-days': {
      id: '/profile/optional-days'
      path: '/profile/optional-days'
      fullPath: '/profile/optional-days'
      preLoaderRoute: typeof ProfileOptionalDaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/measurements': {
      id: '/profile/measurements'
      path: '/profile/measurements'
      fullPath: '/profile/measurements'
      preLoaderRoute: typeof ProfileMeasurementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$sessionId': {
      id: '/history/$sessionId'
      path: '/history/$sessionId'
      fullPath: '/history/$sessionId'
      preLoaderRoute: typeof HistorySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/active-workout/$planId': {
      id: '/active-workout/$planId'
      path: '/active-workout/$planId'
      fullPath: '/active-workout/$planId'
      preLoaderRoute: typeof ActiveWorkoutPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActiveWorkoutPlanIdRoute: ActiveWorkoutPlanIdRoute,
  HistorySessionIdRoute: HistorySessionIdRoute,
  ProfileMeasurementsRoute: ProfileMeasurementsRoute,
  ProfileOptionalDaysRoute: ProfileOptionalDaysRoute,
  ProfileProgressRoute: ProfileProgressRoute,
  WorkoutsPlanIdRoute: WorkoutsPlanIdRoute,
  WorkoutsImportRoute: WorkoutsImportRoute,
  WorkoutsNewRoute: WorkoutsNewRoute,
  ActiveWorkoutIndexRoute: ActiveWorkoutIndexRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  WorkoutsIndexRoute: WorkoutsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
