/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreinosIndexRouteImport } from './routes/treinos/index'
import { Route as TreinoAtivoIndexRouteImport } from './routes/treino-ativo/index'
import { Route as PerfilIndexRouteImport } from './routes/perfil/index'
import { Route as HistoricoIndexRouteImport } from './routes/historico/index'
import { Route as ExerciciosIndexRouteImport } from './routes/exercicios/index'
import { Route as TreinosNovoRouteImport } from './routes/treinos/novo'
import { Route as TreinosImportarRouteImport } from './routes/treinos/importar'
import { Route as TreinosPlanoIdRouteImport } from './routes/treinos/$planoId'
import { Route as TreinoAtivoPlanoIdRouteImport } from './routes/treino-ativo/$planoId'
import { Route as PerfilMedidasRouteImport } from './routes/perfil/medidas'
import { Route as PerfilEvolucaoRouteImport } from './routes/perfil/evolucao'
import { Route as PerfilDiasOpcionaisRouteImport } from './routes/perfil/dias-opcionais'
import { Route as HistoricoSessaoIdRouteImport } from './routes/historico/$sessaoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinosIndexRoute = TreinosIndexRouteImport.update({
  id: '/treinos/',
  path: '/treinos/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoAtivoIndexRoute = TreinoAtivoIndexRouteImport.update({
  id: '/treino-ativo/',
  path: '/treino-ativo/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoIndexRoute = HistoricoIndexRouteImport.update({
  id: '/historico/',
  path: '/historico/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciciosIndexRoute = ExerciciosIndexRouteImport.update({
  id: '/exercicios/',
  path: '/exercicios/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinosNovoRoute = TreinosNovoRouteImport.update({
  id: '/treinos/novo',
  path: '/treinos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinosImportarRoute = TreinosImportarRouteImport.update({
  id: '/treinos/importar',
  path: '/treinos/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinosPlanoIdRoute = TreinosPlanoIdRouteImport.update({
  id: '/treinos/$planoId',
  path: '/treinos/$planoId',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoAtivoPlanoIdRoute = TreinoAtivoPlanoIdRouteImport.update({
  id: '/treino-ativo/$planoId',
  path: '/treino-ativo/$planoId',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilMedidasRoute = PerfilMedidasRouteImport.update({
  id: '/perfil/medidas',
  path: '/perfil/medidas',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilEvolucaoRoute = PerfilEvolucaoRouteImport.update({
  id: '/perfil/evolucao',
  path: '/perfil/evolucao',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilDiasOpcionaisRoute = PerfilDiasOpcionaisRouteImport.update({
  id: '/perfil/dias-opcionais',
  path: '/perfil/dias-opcionais',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoSessaoIdRoute = HistoricoSessaoIdRouteImport.update({
  id: '/historico/$sessaoId',
  path: '/historico/$sessaoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/historico/$sessaoId': typeof HistoricoSessaoIdRoute
  '/perfil/dias-opcionais': typeof PerfilDiasOpcionaisRoute
  '/perfil/evolucao': typeof PerfilEvolucaoRoute
  '/perfil/medidas': typeof PerfilMedidasRoute
  '/treino-ativo/$planoId': typeof TreinoAtivoPlanoIdRoute
  '/treinos/$planoId': typeof TreinosPlanoIdRoute
  '/treinos/importar': typeof TreinosImportarRoute
  '/treinos/novo': typeof TreinosNovoRoute
  '/exercicios/': typeof ExerciciosIndexRoute
  '/historico/': typeof HistoricoIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/treino-ativo/': typeof TreinoAtivoIndexRoute
  '/treinos/': typeof TreinosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historico/$sessaoId': typeof HistoricoSessaoIdRoute
  '/perfil/dias-opcionais': typeof PerfilDiasOpcionaisRoute
  '/perfil/evolucao': typeof PerfilEvolucaoRoute
  '/perfil/medidas': typeof PerfilMedidasRoute
  '/treino-ativo/$planoId': typeof TreinoAtivoPlanoIdRoute
  '/treinos/$planoId': typeof TreinosPlanoIdRoute
  '/treinos/importar': typeof TreinosImportarRoute
  '/treinos/novo': typeof TreinosNovoRoute
  '/exercicios': typeof ExerciciosIndexRoute
  '/historico': typeof HistoricoIndexRoute
  '/perfil': typeof PerfilIndexRoute
  '/treino-ativo': typeof TreinoAtivoIndexRoute
  '/treinos': typeof TreinosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/historico/$sessaoId': typeof HistoricoSessaoIdRoute
  '/perfil/dias-opcionais': typeof PerfilDiasOpcionaisRoute
  '/perfil/evolucao': typeof PerfilEvolucaoRoute
  '/perfil/medidas': typeof PerfilMedidasRoute
  '/treino-ativo/$planoId': typeof TreinoAtivoPlanoIdRoute
  '/treinos/$planoId': typeof TreinosPlanoIdRoute
  '/treinos/importar': typeof TreinosImportarRoute
  '/treinos/novo': typeof TreinosNovoRoute
  '/exercicios/': typeof ExerciciosIndexRoute
  '/historico/': typeof HistoricoIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/treino-ativo/': typeof TreinoAtivoIndexRoute
  '/treinos/': typeof TreinosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/historico/$sessaoId'
    | '/perfil/dias-opcionais'
    | '/perfil/evolucao'
    | '/perfil/medidas'
    | '/treino-ativo/$planoId'
    | '/treinos/$planoId'
    | '/treinos/importar'
    | '/treinos/novo'
    | '/exercicios/'
    | '/historico/'
    | '/perfil/'
    | '/treino-ativo/'
    | '/treinos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/historico/$sessaoId'
    | '/perfil/dias-opcionais'
    | '/perfil/evolucao'
    | '/perfil/medidas'
    | '/treino-ativo/$planoId'
    | '/treinos/$planoId'
    | '/treinos/importar'
    | '/treinos/novo'
    | '/exercicios'
    | '/historico'
    | '/perfil'
    | '/treino-ativo'
    | '/treinos'
  id:
    | '__root__'
    | '/'
    | '/historico/$sessaoId'
    | '/perfil/dias-opcionais'
    | '/perfil/evolucao'
    | '/perfil/medidas'
    | '/treino-ativo/$planoId'
    | '/treinos/$planoId'
    | '/treinos/importar'
    | '/treinos/novo'
    | '/exercicios/'
    | '/historico/'
    | '/perfil/'
    | '/treino-ativo/'
    | '/treinos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoricoSessaoIdRoute: typeof HistoricoSessaoIdRoute
  PerfilDiasOpcionaisRoute: typeof PerfilDiasOpcionaisRoute
  PerfilEvolucaoRoute: typeof PerfilEvolucaoRoute
  PerfilMedidasRoute: typeof PerfilMedidasRoute
  TreinoAtivoPlanoIdRoute: typeof TreinoAtivoPlanoIdRoute
  TreinosPlanoIdRoute: typeof TreinosPlanoIdRoute
  TreinosImportarRoute: typeof TreinosImportarRoute
  TreinosNovoRoute: typeof TreinosNovoRoute
  ExerciciosIndexRoute: typeof ExerciciosIndexRoute
  HistoricoIndexRoute: typeof HistoricoIndexRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
  TreinoAtivoIndexRoute: typeof TreinoAtivoIndexRoute
  TreinosIndexRoute: typeof TreinosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinos/': {
      id: '/treinos/'
      path: '/treinos'
      fullPath: '/treinos/'
      preLoaderRoute: typeof TreinosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino-ativo/': {
      id: '/treino-ativo/'
      path: '/treino-ativo'
      fullPath: '/treino-ativo/'
      preLoaderRoute: typeof TreinoAtivoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/': {
      id: '/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico/': {
      id: '/historico/'
      path: '/historico'
      fullPath: '/historico/'
      preLoaderRoute: typeof HistoricoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercicios/': {
      id: '/exercicios/'
      path: '/exercicios'
      fullPath: '/exercicios/'
      preLoaderRoute: typeof ExerciciosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinos/novo': {
      id: '/treinos/novo'
      path: '/treinos/novo'
      fullPath: '/treinos/novo'
      preLoaderRoute: typeof TreinosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinos/importar': {
      id: '/treinos/importar'
      path: '/treinos/importar'
      fullPath: '/treinos/importar'
      preLoaderRoute: typeof TreinosImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinos/$planoId': {
      id: '/treinos/$planoId'
      path: '/treinos/$planoId'
      fullPath: '/treinos/$planoId'
      preLoaderRoute: typeof TreinosPlanoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino-ativo/$planoId': {
      id: '/treino-ativo/$planoId'
      path: '/treino-ativo/$planoId'
      fullPath: '/treino-ativo/$planoId'
      preLoaderRoute: typeof TreinoAtivoPlanoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/medidas': {
      id: '/perfil/medidas'
      path: '/perfil/medidas'
      fullPath: '/perfil/medidas'
      preLoaderRoute: typeof PerfilMedidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/evolucao': {
      id: '/perfil/evolucao'
      path: '/perfil/evolucao'
      fullPath: '/perfil/evolucao'
      preLoaderRoute: typeof PerfilEvolucaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/dias-opcionais': {
      id: '/perfil/dias-opcionais'
      path: '/perfil/dias-opcionais'
      fullPath: '/perfil/dias-opcionais'
      preLoaderRoute: typeof PerfilDiasOpcionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico/$sessaoId': {
      id: '/historico/$sessaoId'
      path: '/historico/$sessaoId'
      fullPath: '/historico/$sessaoId'
      preLoaderRoute: typeof HistoricoSessaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoricoSessaoIdRoute: HistoricoSessaoIdRoute,
  PerfilDiasOpcionaisRoute: PerfilDiasOpcionaisRoute,
  PerfilEvolucaoRoute: PerfilEvolucaoRoute,
  PerfilMedidasRoute: PerfilMedidasRoute,
  TreinoAtivoPlanoIdRoute: TreinoAtivoPlanoIdRoute,
  TreinosPlanoIdRoute: TreinosPlanoIdRoute,
  TreinosImportarRoute: TreinosImportarRoute,
  TreinosNovoRoute: TreinosNovoRoute,
  ExerciciosIndexRoute: ExerciciosIndexRoute,
  HistoricoIndexRoute: HistoricoIndexRoute,
  PerfilIndexRoute: PerfilIndexRoute,
  TreinoAtivoIndexRoute: TreinoAtivoIndexRoute,
  TreinosIndexRoute: TreinosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
